### ISSUE TITLE
Test status

### ISSUE THREAD

**Issue by lll000111** [wkh237/react-native-fetch-blob-dev#6]
I ran them all on my current code (https://github.com/lll000111/react-native-fetch-blob/tree/0.10.9) and this is the result. I don't think any of those errors are related to anything I did.

#### test-0.5.1
- remove() should work correctly
- dispose() should work correctly

#### test-0.7.0
- "task not canceled" (at the very end)

#### test-0.9.0
- cache control header and range request test => combined file size check
- #73 unicode response BASE64 content test => but on screen "expect" and "actual" strings look exactly equal...???
- request should not retry after timed out

#### test-0.10.0
- cookie test: TypeError: undefined is not an object (evaluating '_reactNativeFetchBlob2.default.net.getCookies')`
- #171 verification (timeout)

#### test-0.10.1
- Invalid promise.resolve call after task is canceled #176
- the rest after the above is skipped

#### test-0.10.5
- #296 Android Download Manager should not crash the app when status code is not 200: 

#### test-0.10.7
- HTTPS request should be cancellable when fileCache or path is set
UPDATE: Today (repeat testing for new commits) this test frags my emulator - I have to "wipe data", Re-installation and restart is not enough)

#### test-background
- background http response (timeout)

#### test-firebase
9 of 10 pass
- Image underneath "download to base64" is not shown (remains gray)
- upload from CameraRoll  Error: Download manager could not resolve downloaded file path.`

#### test-android 
5 of 7 pass
2 x Error: Download manager could not resolve downloaded file path.`

**Comment by wkh237** [comment]
@lll000111 , thanks for the update 👍  Some of the test cases failed simply because the test case itself is incorrect or the API has already changed. IMO, most functions are working, I'll have a look on these ones : 

test-0.9.6
test-0.10.1
test-firebase

**Comment by lll000111** [comment]
0.9.6 is solved - the test tries to delete the test file at the beginning, but it does not exist yet.

I'm adding a final `catch()` to all promises that don't have one too, so that the errors show up INSIDE the GUI and not as yellow or red fullscreen.

**Comment by lll000111** [comment]
I reran the tests because of the new commits I made and update the results above. Unresolved promises (in the test code) and 0.96 are fixed and gone.

**Comment by lll000111** [comment]
Closing because the PR was merged - the PR here for RNFB-dev remains open...
